Dataloader
made-kdd-2021/image-cls pull request #4
Opened 2021-10-25 19:05 UTC by zaitmambet

2021-10-25 19:07 UTC, KernelA commented
@zaitmambet , зачем в Jupyter notebook как я это буду использовать в коде обучения модели?

2021-10-25 19:09 UTC, KernelA requested changes
Нужно переделать, чтобы я мог использовать код в основном проекте. Я не смогу из Jupyter импортировать методы и классы в Python

2021-10-25 19:19 UTC, KernelA commented on dataloader/data_loader.py
> +class XrayDataLoader(utils.data.DataLoader):
Зачем свой Dataloader?

Стандартный и так пойдёт

2021-10-25 19:22 UTC, KernelA commented
Зачем тут два раза добавлены notebook c одним названием?

2021-10-25 19:22 UTC, zaitmambet commented on dataloader/data_loader.py
> +class XrayDataLoader(utils.data.DataLoader):
наверное ты прав, единственное надо как-то передать место хранения данных и их тип (трейн, тест, вал)

2021-10-25 19:23 UTC, KernelA commented on dataloader/data_loader.py
> +class NewPad(object):
Зачем тут своё преобразование, когда есть это?
https://pytorch.org/vision/stable/transforms.html#torchvision.transforms.Pad

2021-10-25 19:24 UTC, KernelA commented on dataloader/data_loader.py
> +data_transforms = {
Это нужно вынести в отдельный файл и передавать как параметр в Dataloader.

Должно быть хотя бы два типа для train и test

2021-10-25 19:24 UTC, KernelA commented on dataloader/data_loader.py
> +        transforms.Grayscale(num_output_channels=3),
Зачем это нужно оно и так в Grayscale?

2021-10-25 19:25 UTC, KernelA commented on dataloader/data_loader.py
> +          self._transform = transforms.Compose([data_transforms['general'], data_transforms['train']])
Это надо в параметрах принимать

2021-10-25 19:26 UTC, zaitmambet commented on dataloader/data_loader.py
> +class NewPad(object):
здесь используется функция get_padding. Но в общем, NewPad() я далее в data_transforms не стал использовать, так что можно убрать

2021-10-25 19:26 UTC, KernelA requested changes
Нужно доделать

2021-10-25 19:28 UTC, zaitmambet commented on dataloader/data_loader.py
> +        transforms.Grayscale(num_output_channels=3),
ты разве не переводил в RGB? проверю

2021-10-25 19:29 UTC, KernelA commented on dataloader/data_loader.py
> +class XrayDataLoader(utils.data.DataLoader):
Тут стандартный всё делает. Нам нет смысла делать свой

2021-10-25 19:29 UTC, zaitmambet commented on dataloader/data_loader.py
> +          self._transform = transforms.Compose([data_transforms['general'], data_transforms['train']])
кстати да, не заметил!

2021-10-25 19:30 UTC, KernelA commented on dataloader/data_loader.py
> +class NewPad(object):
Надо убрать всё лишнее

2021-10-25 19:30 UTC, zaitmambet commented on dataloader/data_loader.py
> +          self._transform = transforms.Compose([data_transforms['general'], data_transforms['train']])
хотя там же выше от параметра зависит: if set_name == 'train':

2021-10-25 19:30 UTC, KernelA commented on dataloader/data_loader.py
> +        transforms.Grayscale(num_output_channels=3),
В том то и дело что при загрузке уже RGB

2021-10-25 19:36 UTC, KernelA commented on dataloader/data_loader.py
> +        transforms.Resize(size=500),
Это должно быть как параметр

2021-10-25 20:02 UTC, KernelA commented on dataloader/data_loader.py
> +          self._transform = transforms.Compose([data_transforms['general'], data_transforms['train']])
Я про сам transform он должен извне передаваться. Нам потом на этапе применения модели нужно иметь возможность использовать отдельно. Если он будет внутри кода глубоко, то мы не сможем использовать

2021-10-28 11:41 UTC, KernelA commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать EDA для изображений](https://trello.com/c/XwnquiJD/17-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-eda-%D0%B4%D0%BB%D1%8F-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9)

2021-10-28 12:26 UTC, KernelA commented
![](https://github.trello.services/images/mini-trello-icon.png) [3 Применение следующих групп методов: gradients, signals, attribution methods (9 баллов)](https://trello.com/c/NzkS7JZl/26-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D1%8E%D1%89%D0%B8%D1%85-%D0%B3%D1%80%D1%83%D0%BF%D0%BF-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2-gradients-signals-attribution-methods-9-%D0%B1%D0%B0%D0%BB%D0%BB%D0%BE%D0%B2)

2021-10-28 12:26 UTC, KernelA commented
![](https://github.trello.services/images/mini-trello-icon.png) [3 Применение следующих групп методов: gradients, signals, attribution methods (9 баллов)](https://trello.com/c/NzkS7JZl/26-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D1%8E%D1%89%D0%B8%D1%85-%D0%B3%D1%80%D1%83%D0%BF%D0%BF-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2-gradients-signals-attribution-methods-9-%D0%B1%D0%B0%D0%BB%D0%BB%D0%BE%D0%B2)

2021-10-31 20:32 UTC, closed without merging

2021-10-31 20:33 UTC, KernelA commented
Все изменения уже есть в другом pull request